<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ADD TO CART_inventory_item_img</name>
   <tag></tag>
   <elementGuidId>05f721a1-47e1-4b25-85d5-8d2b50d7cfbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item_5_img_link > img.inventory_item_img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='item_5_img_link']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#item_5_img_link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2ba6f24d-9769-49e9-a809-a5b7610e8847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inventory_item_img</value>
      <webElementGuid>d9b3cc39-be1c-4e62-808c-1d727b1eb763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./img/sauce-pullover-1200x1500.jpg</value>
      <webElementGuid>6bd7ade4-b756-4975-871d-1f54e25062dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_5_img_link&quot;)/img[@class=&quot;inventory_item_img&quot;]</value>
      <webElementGuid>36b3ae68-d5c0-4a2d-8060-c0a2e2425cd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='item_5_img_link']/img</value>
      <webElementGuid>65283fca-1c2d-4aaf-9c7d-79e61824ab16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/img</value>
      <webElementGuid>c2ad60d0-dfff-4584-88ca-bda235f49cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './img/sauce-pullover-1200x1500.jpg']</value>
      <webElementGuid>a2298383-4f31-452a-b9b3-c1b40b61d879</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
