<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AV-CB-01</name>
   <tag></tag>
   <elementGuidId>2bf9e572-02d9-49a9-9227-678fef198681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Catalog']/table/tbody/tr[2]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;AV-CB-01&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>858757f5-503e-41c4-b6a9-22a70cd3e549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/actions/Catalog.action?viewProduct=&amp;productId=AV-CB-01</value>
      <webElementGuid>f42053b7-1899-4483-b4ec-9479738883ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AV-CB-01</value>
      <webElementGuid>1951f03b-aecb-42f1-8134-5ab055a27fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/table[1]/tbody[1]/tr[2]/td[1]/a[1]</value>
      <webElementGuid>be162cdf-592c-4160-80de-eb9985a446f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/table/tbody/tr[2]/td/a</value>
      <webElementGuid>c2f3b25e-fa16-4bcb-8246-a07aa70d5460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AV-CB-01')]</value>
      <webElementGuid>f20c16fb-d701-4e06-8bbb-529addb035c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::a[1]</value>
      <webElementGuid>19b9a4ed-0d7f-4663-a6ec-a4865d2446ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product ID'])[1]/following::a[1]</value>
      <webElementGuid>11b6c6f2-0f03-41a1-8145-ce14b88a130d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon Parrot'])[1]/preceding::a[1]</value>
      <webElementGuid>a0b32cea-882b-4f62-a5c9-a52df95116ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AV-SB-02'])[1]/preceding::a[1]</value>
      <webElementGuid>fb6d8ca5-04bc-4fb3-b9b6-b14df3eb606e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AV-CB-01']/parent::*</value>
      <webElementGuid>8b189fee-0e27-478c-9cb1-7c02997e4516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/actions/Catalog.action?viewProduct=&amp;productId=AV-CB-01')]</value>
      <webElementGuid>83366e61-b1c6-4968-b25e-55b3c84fecca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>cce2d6a2-9262-4353-96c2-b16c88cc6d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/actions/Catalog.action?viewProduct=&amp;productId=AV-CB-01' and (text() = 'AV-CB-01' or . = 'AV-CB-01')]</value>
      <webElementGuid>48856c6d-4f00-42f8-9c61-5d0f545e1ddf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
